name: salamatiman
description: A new Flutter project.

publish_to: 'none'
version: 1.0.5+1006

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  http: ^0.13.4
  dio: ^4.0.6
  get: ^4.6.5
  animate_icons: ^2.0.0
  persian_number_utility: ^1.1.1
  cupertino_icons: ^1.0.5
  activity_recognition_flutter: ^4.2.0
  permission_handler: ^9.2.0
  pedometer: ^3.0.0
  animated_bottom_navigation_bar: ^0.3.2
  get_storage: ^2.0.3
  fluttertoast: ^8.0.9
  sms_autofill: ^2.2.0
  flutter_svg: ^1.0.3
  syncfusion_flutter_sliders: ^20.1.50
  flutter_echarts: ^2.3.0
  flutter_spinkit: ^5.1.0
  jwt_decoder: ^2.0.1
  flutter_awesome_buttons: ^1.1.0
  flutter_neumorphic: ^3.2.0
  modal_bottom_sheet: ^2.0.1
  dropdown_button2: ^1.5.0
  shimmer: ^2.0.0
  pie_chart: ^5.3.0
  cached_network_image: ^3.2.1
  flutter_slidable: ^1.2.1
  awesome_dialog: ^2.2.1
  sleek_circular_slider: ^2.0.1
  awesome_notifications: ^0.6.21
  numberpicker: ^2.1.1
  dotted_border: ^2.0.0+2
  flutter_staggered_grid_view: ^0.6.1
  syncfusion_flutter_charts: ^20.1.60+1
  expandable_page_view: ^1.0.14
  flutter_html: ^3.0.0-alpha.5
  url_launcher: ^6.1.3
  flutter_inappwebview: ^5.4.3+7
  file_picker: ^4.6.1
  flutter_sound: ^9.2.13
  just_audio: ^0.9.26
  audio_video_progress_bar: ^0.10.0
  better_player: ^0.0.83
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  android_alarm_manager_plus: ^2.0.6
  path_provider: ^2.0.11
  intl: ^0.17.0
  wave: ^0.2.2
  widget_mask: ^1.0.0+0
  uni_links: ^0.5.1
  linked_scroll_controller: ^0.2.0
  custom_refresh_indicator: ^1.2.1
  shamsi_date: ^1.0.1
  flutter_zoom_drawer: ^3.0.3
  sqflite: ^2.2.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/profile.png
    - assets/images/social/
    - assets/images/activity/
    - assets/images/vadeh/
    - assets/images/target/
    - assets/images/chat/
    - assets/images/pay/
    - assets/images/biometric/
    - assets/images/quick-access/
    - assets/images/plan/
    - assets/images/ratting/
  fonts:
    - family: dana
      fonts:
        - asset: assets/fonts/dana/dana-medium.ttf
        - asset: assets/fonts/dana/dana-light.ttf
        - asset: assets/fonts/dana/dana-bold.ttf
        - asset: assets/fonts/dana/dana-black.ttf
    - family: vazir
      fonts:
        - asset: assets/fonts/Vazirmatn-Medium.ttf
    - family: vaziradad
      fonts:
        - asset: assets/fonts/vaziradad.ttf
    - family: BottomNavigationBarIcon
      fonts:
        - asset: assets/fonts/BottomNavigationBarIcon.ttf

